### ISSUE TITLE
Chef::Exceptions::Package: No candidate version available for libarchive-devel

### ISSUE THREAD

**Issue by marc-** [chef-cookbooks/libarchive#19]
Getting this error on Red Hat Enterprise Linux Server release 7.1 (Maipo) on AWS:

```
==> vault:     * libartifact_file[vault-0.2.0] action create
==> vault:     Recipe: libarchive::default
==> vault:       * yum_package[libarchive-devel] action upgrade
==> vault:         * No candidate version available for libarchive-devel
==> vault:         ================================================================================
==> vault:         Error executing action `upgrade` on resource 'yum_package[libarchive-devel]'
==> vault:         ================================================================================
==> vault:         
==> vault:         Chef::Exceptions::Package
==> vault:         -------------------------
==> vault:         No candidate version available for libarchive-devel
```

```
$ yum search libarchive
=============================================== N/S matched: libarchive ================================================
libarchive.i686 : A library for handling streaming archive formats
libarchive.x86_64 : A library for handling streaming archive formats
```

Though, it works just fine for CentOS 7.1 .

**Comment by jwadolowski** [comment]
Same issues on RHEL 6.7, however worked perfectly fine on CentOS 6.7 in test kitchen. Quick and easy workaround is to set `node['libarchive']['package_name']` in your wrapper cookbook.

**Comment by johnbellone** [comment]
I wonder if this is on epel?

**Comment by marc-** [comment]
As far as I'm aware it is not. Though I don't have RHEL distr at my possession at the moment to double check that.

**Comment by xmik** [comment]
I got the same error today in docker container (made from `phusion/baseimage:0.9.17` docker image, so **ubuntu:14.04**) for `libarchive-dev` package:
```
apt_package[libarchive-dev] (libarchive::default line 13) had an error: Chef::Exceptions::Package: No candidate version available for libarchive-dev
```
Inside that container, this command returns nothing:
```
# apt-cache search libarchive-dev
```

### Solution for Ubuntu/Debian
Running: `apt-get update` solved this. The solution to be applied in a cookbook is to set this attribute: `override['apt']['compile_time_update'] = true` and to
`include_recipe 'apt::default'` before including any libarchive cookbook recipes.

**Comment by iennae** [comment]
For debian platform systems you can do 

> apt_update 'update' do
> end.run_action(:update) if platform_family?('debian')

prior to the inclusion of any resources in this cookbook and that should solve this problem (as long as you are using chef-client 12.7+, otherwise use the apt cookbook as mentioned in the prior comment).

I'm not seeing an issue on centos issues with the current version of the cookbook, so I'm going to go ahead and close this now.
