### ISSUE TITLE
Error executing action `upgrade` on resource 'windows_package[libarchive]

### ISSUE THREAD

**Issue by lioramilbaum** [chef-cookbooks/libarchive#24]
Chef::Exceptions::UnsupportedAction[0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com -----------------------------------[0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com #Chef::Provider::Package::Windows:0x00000004cd6500 does not support :upgrade[0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com 
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0mCookbook Trace:[0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com ---------------[0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com c:/chef/cache/cookbooks/libarchive/recipes/default.rb:16:in `from_file'
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0mc:/chef/cache/cookbooks/Poker/recipes/client.rb:5:in`from_file'[0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com 
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0mResource Declaration:[0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com ---------------------[0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com # In c:/chef/cache/cookbooks/libarchive/recipes/default.rb
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 13: package node['libarchive']['package_name'] do
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 14:   version node['libarchive']['package_version'] if node['libarchive']['package_version']
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 15:   action :nothing
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 16: end.run_action(:upgrade)
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 17: 
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 18: if Chef::Resource::ChefGem.instance_methods(false).include?(:compile_time)
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 19:   chef_gem 'ffi-libarchive' do
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 20:     version '~> 0.2.0'
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 21:     compile_time true
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 22:   end
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 23: else
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 24:   chef_gem 'ffi-libarchive' do
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 25:     version '~> 0.2.0'
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 26:     action :nothing
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 27:   end.run_action(:install)
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m 28: end
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0mCompiled Resource:[0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com ------------------[0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com # Declared in c:/chef/cache/cookbooks/libarchive/recipes/default.rb:13:in `from_file'
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0mwindows_package("libarchive") do
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m  package_name "libarchive"
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m  action [:nothing]
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m  retries 0
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m  retry_delay 2
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m  default_guard_interpreter :default
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m  declared_type :package
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m  cookbook_name "libarchive"
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m  recipe_name "default"
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m  returns [0]
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0mend
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com [0mPlatform:[0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com ---------[0m
ec2-176-34-200-3.eu-west-1.compute.amazonaws.com x64-mingw32[0m

**Comment by iennae** [comment]
Hi, this cookbook has recently come under the purview of the community engineering team at Chef. I'm wondering if this is still a problem for you? It looks like you might be trying to do something with windows and this cookbook, and this cookbook hasn't been written to support the windows platform explicitly. Thanks!

**Comment by lioramilbaum** [comment]
Is there a different cookbook which also supports windows?

**Comment by iennae** [comment]
I'm not sure what you are explicitly trying to do so it's hard to recommend a specific cookbook. There is potentially the ark cookbook. I'm going to go ahead and close this issue.
