### ISSUE TITLE
v0.7.0 vs v0.7.1 question

### ISSUE THREAD

**Issue by pantocrator27** [chef-cookbooks/libarchive#31]
There appears to be a difference in supported Chef Client versions between v0.7.0 which states it supports Chef Client ~> 12.1 vs v0.7.1 which states its supports Chef Client ~> 12.7.  Just out of curiosity, in looking at the diffs, I cannot see where anything committed would make that difference.

**Comment by iennae** [comment]
The bug with version 0.7.0 is that I didn't update the metadata to reflect that converting to using custom resources requires a minimum version of Chef. No change was made in 0.7.1 other than the metadata change.

**Comment by pantocrator27** [comment]
According to https://docs.chef.io/custom_resources.html, Chef Custom resources after 12.5+.

**Comment by pantocrator27** [comment]
@iennae due to Chef Custom Resources being introduced in Chef 12.5, I think it may be safe to bump this back to 12.5 ...

**Comment by iennae** [comment]
Yep, as it's not using action_class without the class_eval it's technically good for 12.5+. Rather than re-releasing with another version bump though I'm going to leave it as is.

**Comment by pantocrator27** [comment]
@iennae can the documentation and metadata.rb at least be modified when the next version bump will happen so that people will know ... Thanks!
