### ISSUE TITLE
libarchive package install fails because apt-cache is out of sync (workaround: manual apt-get update)

### ISSUE THREAD

**Issue by lehn-etracker** [chef-cookbooks/libarchive#32]
### Cookbook version
Using libarchive (1.0.0)

### Chef-client version
12.21.1

### Platform Details
- debian/jessie64
- vagrant
- virtualbox

### Scenario:
- Imagine, you have a up and running Debian Jessie with outdated apt package lists
- now try to include any cookbook/recipe which uses libarchive
- it will fail, because the package gets installed via end.run_action(:upgrade) in point without giving you a chance to push apt::default in front of the runlist

### Steps to Reproduce:
- setup a debian/jessie64
- wait until debian packages lists become out of sync and libarchive gets updates
- try to use https://github.com/adamkrone/chef-consul-template (which uses libarchive)
- it will fail, because file of libarchive version is no more available at the package repository

### Expected Result:
- it should update package-list like apt::default usually does
- and finally successful converge

### Actual Result:
- apt-get install libarchive-dev fails

**Comment by lehn-etracker** [comment]
## My workaround

```ruby
# load apt
include_recipe 'apt::default'

# force updating apt package lists
execute 'apt-get update enforcement' do
  command 'apt-get update'
  action :nothing
end.run_action(:run)
```

**Comment by tas50** [comment]
@lehn-etracker Thanks for the report, but this is the underlying issue with how Debian works and how chef installs packages. You'll need to make sure that apt is updated early on in your Chef runs. We have an apt_update resource now built into chef so if you include something like this in a base cookbook or wrapper cookbook you'll be good to go:

```ruby
apt_update 'update'
```
