### ISSUE TITLE
libarchive just doesn't work

### ISSUE THREAD

**Issue by ton31337** [chef-cookbooks/libarchive#33]
### Cookbook version
2.0.0

### Chef-client version
14.2.0

### Platform Details
CentOS Linux release 7.4.1708 (Core) 

### Scenario:
kitchen converge

### Steps to Reproduce:
$ git clone https://github.com/adamkrone/chef-consul-template
$ kitchen converge

```
       Recipe: consul-template::install_binary
         * remote_file[/tmp/kitchen/cache/consul-template_0.19.4_linux_amd64.zip] action create_if_missing (up to date)
         * archive_file[consul-template_0.19.4_linux_amd64.zip] action extract
         
         Running handlers:
       [2018-06-18T17:02:31+00:00] ERROR: Running exception handlers
         Running handlers complete
       [2018-06-18T17:02:31+00:00] ERROR: Exception handlers complete
         Chef Client failed. 0 resources updated in 03 seconds
       [2018-06-18T17:02:31+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-06-18T17:02:31+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-06-18T17:02:31+00:00] FATAL: LoadError: Could not open library 'libarchive.so.13': /lib64/liblzma.so.5: version `XZ_5.2' not found (required by /opt/chef/embedded/lib/libarchive.so.13).
       Could not open library 'libarchive.13': libarchive.13: cannot open shared object file: No such file or directory.
       Could not open library 'libarchive.13.so': libarchive.13.so: cannot open shared object file: No such file or directory.
       Could not open library 'libarchive.so': /lib64/liblzma.so.5: version `XZ_5.2' not found (required by /opt/chef/embedded/lib/libarchive.so).
       Could not open library 'libarchive': libarchive: cannot open shared object file: No such file or directory.
       Could not open library 'archive': archive: cannot open shared object file: No such file or directory
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <install-only-centos-74>.  Please see .kitchen/logs/install-only-centos-74.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by eknudtson** [comment]
This is failing for me as well on Centos 7.5.

**Comment by siulcode** [comment]
Is there any pending WIP for this? 

I'm having a similar issue for Chef 14. 

`       [2018-08-01T00:01:52+00:00] FATAL: LoadError: Could not open library 'archive': archive: cannot open shared object file: No such file or directory.
       Could not open library 'libarchive.so': /lib64/liblzma.so.5: version `XZ_5.2' not found (required by /opt/chef/embedded/lib/libarchive.so).
       Could not open library 'libarchive.so.2': libarchive.so.2: cannot open shared object file: No such file or directory
       [2018-08-01T00:01:52+00:00] FATAL: LoadError: Could not open library 'archive': archive: cannot open shared object file: No such file or directory.
       Could not open library 'libarchive.so': /lib64/liblzma.so.5: version `XZ_5.2' not found (required by /opt/chef/embedded/lib/libarchive.so).
       Could not open library 'libarchive.so.2': libarchive.so.2: cannot open shared object file: No such file or directory`

**Comment by siulcode** [comment]
Hi there, 

It looks like this thread is dead. Is there any way to get the maintainers to look into this issue?

**Comment by bdwyertech** [comment]
Wonder if it's got to do with this directory not getting bundled with mixlib-archive gem -- https://github.com/chef/mixlib-archive/tree/master/distro/ruby_bin_folder

**Comment by bdwyertech** [comment]
Me thinks the next version of Chef with updates `mixlib-archive` gem will resolve this...

https://github.com/chef/mixlib-archive/pull/33
